2021-12-26 12:56:02,180 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2021-12-26 12:56:33,191 django.request 222 WARNING  Not Found: /favicon.ico
2021-12-26 13:50:24,114 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 13:45:43,778 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 13:50:05,577 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 13:50:06,102 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 13:50:20,809 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 13:50:21,402 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 13:50:49,497 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 13:56:56,260 django.request 222 WARNING  Not Found: /login
2024-05-23 13:56:56,675 django.request 222 WARNING  Not Found: /favicon.ico
2024-05-23 14:00:30,818 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 14:00:31,516 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:00:47,492 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 14:00:48,348 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:01:46,796 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 14:01:47,546 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:02:00,340 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 14:03:51,373 django.request 222 ERROR    Internal Server Error: /book-list
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 14:05:32,425 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 14:05:33,148 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:06:00,192 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 14:16:31,050 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\core\settings.py changed, reloading.
2024-05-23 14:16:32,693 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:24:28,290 django.request 222 ERROR    Internal Server Error: /charts/
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 166, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 14:25:54,089 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 14:25:54,773 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:25:57,841 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 14:25:58,527 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:34:58,781 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:40:50,613 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 14:55:11,715 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 14:57:52,172 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 15:02:47,712 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 15:04:46,421 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 15:07:45,331 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 15:07:46,039 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:08:26,481 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 15:08:27,119 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:08:38,961 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 15:08:39,701 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:09:05,223 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 15:09:05,867 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:09:15,289 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py changed, reloading.
2024-05-23 15:09:15,970 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:09:27,707 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 15:17:59,616 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-23 15:35:34,010 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\authentication\views.py changed, reloading.
2024-05-23 15:35:34,735 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:35:36,920 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:36:01,722 django.utils.autoreload 217 INFO     E:\CodingProjects\Python\Library-main\Library-main\authentication\views.py changed, reloading.
2024-05-23 15:36:02,441 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-05-23 15:36:29,266 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\CodingProjects\Python\Library-main\Library-main\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\Coding\Anaconda3\envs\py310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Coding\Anaconda3\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-06-07 15:48:56,642 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 15:50:05,136 django.request 222 WARNING  Not Found: /login
2024-06-07 15:50:05,239 django.request 222 WARNING  Not Found: /favicon.ico
2024-06-07 16:04:41,975 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:07:07,194 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:07:15,888 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-06-07 16:08:29,712 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:09:12,319 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:12:37,506 django.security.csrf 222 WARNING  Forbidden (CSRF token missing or incorrect.): /auth/login/
2024-06-07 16:17:28,962 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:17:38,245 django.request 222 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\book\views.py", line 104, in get
    return render(request, self.template_name, self.context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-06-07 16:19:01,118 django.utils.autoreload 597 INFO     Watching for file changes with StatReloader
2024-06-07 16:38:52,014 django.request 222 ERROR    Internal Server Error: /user/profile-create/
Traceback (most recent call last):
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\bigdatamovie\ShipandFacedetection\book\templatetags\book_extras.py", line 40, in show_weather
    r = requests.get(url).json()
  File "D:\bigdatamovie\ShipandFacedetection\envname\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\h'x\.conda\envs\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
